# Generated by Django 4.2.30 on 2026-04-19 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_checkin', models.DateField(verbose_name="Date d'arrivée")),
                ('date_checkout', models.DateField(verbose_name='Date de départ')),
                ('prix_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix total (MAD)')),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.chambre', verbose_name='Chambre')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-date_checkin'],
            },
        ),
    ]
